name: shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.3.0 <4.0.0'

# - - - - - - - - - -  PACKAGES - - - - - - - - - #

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1

# - - - - - - - - - -  PACKAGES - - - - - - - - - #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # - - - - - -  LOCAL ASSETS - - - - - - #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
  
  # - - - - - -  LOCAL FONTS - - - - - - #
  fonts:
    - family: reem
      fonts:
        - asset: assets/fonts/Reem.ttf
          weight: 500


